name: AQI Auto Collector

on:
  schedule:
    - cron: "*/5 * * * *"   # mỗi 5 phút
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Call AQI API
        run: |
          curl "https://agreeable-river-0990df500.6.azurestaticapps.net/api/GetRealtimeData?lat=21.0152&lon=105.7999"
