name: Collect AQI Data (Cron)

on:
  schedule:
    - cron: "*/5 * * * *"   # mỗi 5 phút
  workflow_dispatch:        # cho phép bấm chạy tay

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Call Realtime AQI API
        run: |
          curl -X GET "https://agreeable-river-0990df500.6.azurestaticapps.net/api/GetRealtimeData?lat=21.0152&lon=105.7999"
